openapi: "3.0.2"
info:
  title: Basic objects
  version: "1.0"


components:
  schemas:
    error:
      type: object
      properties:
        status:
          type: string
          description: Single string based code describing the error.
        message:
          type: string
          description: Human readable error message.
      required:
        - status
        - message

    address:
      type: object
      properties:
        street:
          type: string
        postalCode:
          type: string
        city:
          type: string
        country:
          type: string
          description: ISO 3166 Alpha 2 code in uppercase letters (DE for Germany, US for United States of America, ...).
          example: DE
      required:
        - street
        - postalCode
        - city
        - country

    userWithoutId:
      type: object
      properties:
        email:
          type: string
        salutation:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        address:
          $ref: "#/components/schemas/address"
