openapi: "3.0.2"
info:
  title: DEMO API
  description: >
    This API can be used to manage users

  version: "1.0"

components:

  schemas:
    # moad-mixin:begin:other.yml:components/schemas>address,userWithoutId
    # WARNING The following was automatically written into this file.
    # It will be replaced by moad with the content of other.yml -> components/schemas>address,userWithoutId
    address:
      type: object
      properties:
        street:
          type: string
        postalCode:
          type: string
        city:
          type: string
        country:
          type: string
          description: ISO 3166 Alpha 2 code in uppercase letters (DE for Germany, US
            for United States of America, ...).
          example: DE
      required:
      - street
      - postalCode
      - city
      - country
    userWithoutId:
      type: object
      properties:
        email:
          type: string
        salutation:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        address:
          $ref: '#/components/schemas/address'
    # End of autogenerated content of other.yml -> components/schemas>address,userWithoutId
    # moad-mixin:end
    specialError:
      # moad-mixin:begin:other.yml:components/schemas/error
      # WARNING The following was automatically written into this file.
      # It will be replaced by moad with the content of other.yml -> components/schemas/error
      type: object
      properties:
        status:
          type: string
          description: Single string based code describing the error.
        message:
          type: string
          description: Human readable error message.
      required:
      - status
      - message
      # End of autogenerated content of other.yml -> components/schemas/error
      # moad-mixin:end
